name: osg-cuda
channels:
  - pytorch
  - huggingface
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.12
  - pandas
  - numpy
  - pyyaml
  - datasets
  - cuda-toolkit
  - pytorch-cuda=11.8
  - pytorch=2.2
  - jupyter
  - ipykernel
  - matplotlib
  - transformers>=4.40.1
  - pip
  - spacy
  - ruff
  - pip:
      - -e .  # For development purposes
